export const cities = [
  {
    name: "New York City",
    country: "USA",
    image:
      "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "The city that never sleeps, famous for Times Square and Central Park.",
    airport: {
      id: "1",
      name: "John F. Kennedy International Airport",
      city: "New York City",
      country: "USA",
      iata_code: "JFK",
      icao_code: "KJFK",
      latitude: "40.641766",
      longitude: "-73.780968",
      altitude: "13",
      timezone_offset: "-5",
      dst: "A",
      timezone: "America/New_York",
      type: "airport",
      source: "OurAirports",
    },
  },
  {
    name: "Paris",
    country: "France",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1773&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "The city of love, known for the Eiffel Tower and Louvre Museum.",
    airport: {
      id: "2",
      name: "Charles de Gaulle Airport",
      city: "Paris",
      country: "France",
      iata_code: "CDG",
      icao_code: "LFPG",
      latitude: "49.009690",
      longitude: "2.547925",
      altitude: "392",
      timezone_offset: "1",
      dst: "E",
      timezone: "Europe/Paris",
      type: "airport",
      source: "OurAirports",
    },
  },
  {
    name: "Tokyo",
    country: "Japan",
    image:
      "https://images.unsplash.com/photo-1547448526-5e9d57fa28f7?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "A bustling metropolis blending tradition and modernity.",
    airport: {
      id: "3",
      name: "Tokyo Haneda Airport",
      city: "Tokyo",
      country: "Japan",
      iata_code: "HND",
      icao_code: "RJTT",
      latitude: "35.549393",
      longitude: "139.779839",
      altitude: "21",
      timezone_offset: "9",
      dst: "N",
      timezone: "Asia/Tokyo",
      type: "airport",
      source: "OurAirports",
    },
  },
  {
    name: "Dubai",
    country: "UAE",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "Known for luxury shopping, ultramodern architecture, and vibrant nightlife.",
    airport: {
      id: "4",
      name: "Dubai International Airport",
      city: "Dubai",
      country: "UAE",
      iata_code: "DXB",
      icao_code: "OMDB",
      latitude: "25.253174",
      longitude: "55.365673",
      altitude: "62",
      timezone_offset: "4",
      dst: "N",
      timezone: "Asia/Dubai",
      type: "airport",
      source: "OurAirports",
    },
  },
  {
    name: "Sydney",
    country: "Australia",
    image:
      "https://images.unsplash.com/photo-1551352912-484163ad5be9?q=80&w=1771&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Famous for the Sydney Opera House and stunning beaches.",
    airport: {
      id: "5",
      name: "Sydney Kingsford Smith Airport",
      city: "Sydney",
      country: "Australia",
      iata_code: "SYD",
      icao_code: "YSSY",
      latitude: "-33.939922",
      longitude: "151.175276",
      altitude: "21",
      timezone_offset: "10",
      dst: "O",
      timezone: "Australia/Sydney",
      type: "airport",
      source: "OurAirports",
    },
  },
  {
    name: "Barcelona",
    country: "Spain",
    image:
      "https://images.unsplash.com/photo-1564221710304-0b37c8b9d729?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description:
      "A vibrant city famous for its Gaudí architecture, stunning beaches, and rich culture.",
    airport: {
      id: "6",
      name: "Barcelona–El Prat Airport",
      city: "Barcelona",
      country: "Spain",
      iata_code: "BCN",
      icao_code: "LEBL",
      latitude: "41.297445",
      longitude: "2.083289",
      altitude: "12",
      timezone_offset: "1",
      dst: "E",
      timezone: "Europe/Madrid",
      type: "airport",
      source: "OurAirports",
    },
  },
];
